name: quote_vyuh_workspace
description: A Vyuh Flutter project created by Vyuh CLI.


packages:
  - plugins/*
  - features/*
  - features/*/*
  - packages/*
  - apps/*

command:
  version:
    workspaceChangelog: false
